<?php

$fallback = filter_fallback_format();
$all = filter_formats();
$for_account = filter_formats($account);
$roles = filter_get_roles_by_format($format);
$formats = filter_get_formats_by_role($rid);
$default_id = filter_default_format();
$default_id_account = filter_default_format($account);
?>
-----
<?php

$fallback = filter_fallback_format();
$all = filter_formats();
$for_account = filter_formats($account);
$roles = filter_get_roles_by_format($format);
$formats = filter_get_formats_by_role($rid);
$default_id = filter_default_format();
$default_id_account = filter_default_format($account);
?>
