<?php

locale_translate_batch_build($files, $options);
locale_config_batch_update_components($options, $langcodes, $components, $update_default_config_langcodes);
locale_translation_check_projects_batch($projects, $langcodes);
?>
-----
<?php

locale_translate_batch_build($files, $options);
locale_config_batch_update_components($options, $langcodes, $components, $update_default_config_langcodes);
locale_translation_check_projects_batch($projects, $langcodes);
?>
