<?php

// locale_config_batch_refresh_name used in various expression positions.
locale_config_batch_refresh_name($names, $langcodes, $context);

$result = locale_config_batch_refresh_name($names, $langcodes, $context);

if (locale_config_batch_refresh_name($names, $langcodes, $context)) {
    doSomething();
}

$items[] = locale_config_batch_refresh_name($names, $langcodes, $context);

?>
-----
<?php

// locale_config_batch_refresh_name used in various expression positions.
locale_config_batch_update_config_translations($names, $langcodes, $context);

$result = locale_config_batch_update_config_translations($names, $langcodes, $context);

if (locale_config_batch_update_config_translations($names, $langcodes, $context)) {
    doSomething();
}

$items[] = locale_config_batch_update_config_translations($names, $langcodes, $context);

?>
