<?php

use Drupal\Tests\field\Traits\EntityReferenceTestTrait;

class EntityReferenceItemTest extends FieldKernelTestBase {

    use EntityReferenceTestTrait;

}

?>
-----
<?php

use Drupal\Tests\field\Traits\EntityReferenceFieldCreationTrait;
use Drupal\Tests\field\Traits\EntityReferenceTestTrait;

class EntityReferenceItemTest extends FieldKernelTestBase {

    use EntityReferenceFieldCreationTrait;

}
