<?php

/** @var \Drupal\node\NodeTypeInterface $nodeType */
$nodeType->setPreviewMode(DRUPAL_DISABLED);
$nodeType->setPreviewMode(DRUPAL_OPTIONAL);
$nodeType->setPreviewMode(DRUPAL_REQUIRED);
$nodeType->setPreviewMode(0);
$nodeType->setPreviewMode(1);
$nodeType->setPreviewMode(2);

?>
-----
<?php

/** @var \Drupal\node\NodeTypeInterface $nodeType */
$nodeType->setPreviewMode(DRUPAL_DISABLED);
$nodeType->setPreviewMode(DRUPAL_OPTIONAL);
$nodeType->setPreviewMode(DRUPAL_REQUIRED);
$nodeType->setPreviewMode(0);
$nodeType->setPreviewMode(1);
$nodeType->setPreviewMode(2);

?>
