<?php

locale_translation_flush_projects();
locale_translation_build_projects();
locale_translation_check_projects();
locale_translation_check_projects(['drupal'], ['de']);
locale_translation_check_projects_local(['drupal'], ['de']);
?>
-----
<?php

locale_translation_flush_projects();
locale_translation_build_projects();
locale_translation_check_projects();
locale_translation_check_projects(['drupal'], ['de']);
locale_translation_check_projects_local(['drupal'], ['de']);
?>
