# Contains automatic fixes for some deprecations introduced in Drupal 8.7.
services:
  DrupalRector\Rector\Deprecation\FilePrepareDirectoryRector: ~
  DrupalRector\Rector\Deprecation\FileCreateDirectoryRector: ~
  DrupalRector\Rector\Deprecation\FileUnmanagedCopyRector: ~
  DrupalRector\Rector\Deprecation\FileExistsReplaceRector: ~
