<?php

declare(strict_types=1);

/**
 * Walk src/ + config/ for PHPSTAN_MESSAGES declarations and emit a
 * normalized registry at config/coverage-registry.php.
 *
 * Sources scanned:
 *
 *   src/Drupal{8,9,10,11}/Rector/Deprecation/<*>Rector.php
 *     — public const PHPSTAN_MESSAGES on the rector class.
 *
 *   config/drupal-{8,9,10,11}/<file>.php
 *     — // PHPSTAN_MESSAGES: comment block above a ruleWithConfiguration()
 *       or rule() call. Used for config-only rector registrations (e.g.
 *       FunctionToServiceRector, RenameClassRector) where there is no
 *       custom rector class to attach a const to.
 *
 * Output: config/coverage-registry.php is a `return [ ... ]` file mapping
 * each rector class name (short, e.g. "ReplaceSessionManagerDeleteRector")
 * to an array of normalized PHPStan deprecation message strings.
 *
 * Consumers (e.g. a future upgrade_status PR) can require this file and
 * flatten via array_merge(...array_values($registry)) for a drop-in
 * replacement of DeprecationAnalyzer::isRectorCovered()'s hardcoded array.
 */
$repoRoot = realpath(__DIR__.'/..');
if ($repoRoot === false) {
    fwrite(STDERR, "Could not resolve repo root\n");
    exit(1);
}

require_once $repoRoot.'/scripts/normalize-phpstan-message.php';

$autoload = $repoRoot.'/vendor/autoload.php';
if (!is_file($autoload)) {
    fwrite(STDERR, "Run `composer install` first — vendor/autoload.php is missing.\n");
    exit(1);
}
require_once $autoload;

$registry = [];

// --- Source 1: PHPSTAN_MESSAGES const on rector classes ---------------------
$srcGlobs = [
    $repoRoot.'/src/Drupal8/Rector/Deprecation/*.php',
    $repoRoot.'/src/Drupal9/Rector/Deprecation/*.php',
    $repoRoot.'/src/Drupal10/Rector/Deprecation/*.php',
    $repoRoot.'/src/Drupal11/Rector/Deprecation/*.php',
];
foreach ($srcGlobs as $glob) {
    foreach (glob($glob) ?: [] as $file) {
        $fqcn = fqcnFromFile($file);
        if ($fqcn === null) {
            continue;
        }
        try {
            $reflection = new ReflectionClass($fqcn);
        } catch (ReflectionException) {
            continue;
        }
        if (!$reflection->hasConstant('PHPSTAN_MESSAGES')) {
            continue;
        }
        $messages = $reflection->getConstant('PHPSTAN_MESSAGES');
        if (!is_array($messages) || $messages === []) {
            continue;
        }
        $short = $reflection->getShortName();
        foreach ($messages as $msg) {
            if (!is_string($msg) || $msg === '') {
                continue;
            }
            $registry[$short][] = normalizePhpstanMessage($msg);
        }
    }
}

// --- Source 2: // PHPSTAN_MESSAGES: blocks in config/drupal-N/*.php --------
$configGlobs = [
    $repoRoot.'/config/drupal-8/*.php',
    $repoRoot.'/config/drupal-9/*.php',
    $repoRoot.'/config/drupal-10/*.php',
    $repoRoot.'/config/drupal-11/*.php',
];
foreach ($configGlobs as $glob) {
    foreach (glob($glob) ?: [] as $file) {
        foreach (extractConfigMessages($file) as $rector => $messages) {
            foreach ($messages as $msg) {
                $registry[$rector][] = normalizePhpstanMessage($msg);
            }
        }
    }
}

// Deduplicate + sort within each rector, sort rectors alphabetically.
foreach ($registry as $rector => $messages) {
    $messages = array_values(array_unique($messages));
    sort($messages);
    $registry[$rector] = $messages;
}
ksort($registry);

// Emit the registry file.
$outPath = $repoRoot.'/config/coverage-registry.php';
$header = <<<'PHP'
<?php

declare(strict_types=1);

/**
 * Auto-generated by scripts/generate-coverage-registry.php.
 *
 * Do not edit by hand. Source of truth:
 *   - public const PHPSTAN_MESSAGES on each rector class
 *   - // PHPSTAN_MESSAGES: comment blocks above config-only registrations
 *
 * Messages are stored AFTER applying the three normalization transforms
 * upgrade_status's DeprecationAnalyzer::categorizeMessage() applies before
 * isRectorCovered(): whitespace collapse, ":\s+(in|as of)" → ". Deprecated
 * \1", and "Use \Drupal" → "Use Drupal".
 *
 * Consumers can require this file and either iterate by rector class, or
 * flatten with array_merge(...array_values($registry)) to get a flat list
 * of all covered deprecation strings.
 */

return
PHP;
$body = var_export($registry, true).";\n";
file_put_contents($outPath, $header.' '.$body);

$flatCount = array_sum(array_map('count', $registry));
echo sprintf(
    "Wrote %s\n  rectors: %d   messages: %d\n",
    $outPath,
    count($registry),
    $flatCount,
);

// ----------------------------------------------------------------------------

/**
 * Cheap namespace + classname extractor from a PHP file.
 *
 * Returns the FQ class name or null if no class declaration found.
 */
function fqcnFromFile(string $file): ?string
{
    $src = file_get_contents($file);
    if ($src === false) {
        return null;
    }
    if (!preg_match('/^\s*namespace\s+([A-Za-z0-9_\\\\]+)\s*;/m', $src, $nsMatch)) {
        return null;
    }
    if (!preg_match('/^\s*(?:final\s+|abstract\s+)?class\s+([A-Za-z0-9_]+)/m', $src, $clMatch)) {
        return null;
    }

    return $nsMatch[1].'\\'.$clMatch[1];
}

/**
 * Extract PHPSTAN_MESSAGES comment blocks from a config file.
 *
 * Expected shape:
 *
 *   // PHPSTAN_MESSAGES <RectorShortName>:
 *   //   <message line 1>
 *   //   <message line 2>
 *   $rectorConfig->ruleWithConfiguration(...);
 *
 * The rector name on the header line is required so one config file can
 * register multiple rectors with separate message lists.
 *
 * @return array<string, list<string>> rector short name => messages
 */
function extractConfigMessages(string $file): array
{
    $src = file_get_contents($file);
    if ($src === false) {
        return [];
    }
    $result = [];
    if (!preg_match_all(
        '!^[ \t]*//\s*PHPSTAN_MESSAGES\s+([A-Za-z0-9_]+):\s*$\n((?:[ \t]*//[^\n]*\n)+)!m',
        $src,
        $matches,
        PREG_SET_ORDER
    )) {
        return [];
    }
    foreach ($matches as $m) {
        $rector = $m[1];
        $messageLines = [];
        foreach (preg_split('/\R/', trim($m[2])) as $line) {
            // Strip the `//` prefix and one optional space.
            if (!preg_match('!^\s*//\s?(.*)$!', $line, $lineMatch)) {
                continue;
            }
            $content = rtrim($lineMatch[1]);
            if ($content === '') {
                continue;
            }
            $messageLines[] = $content;
        }
        // Each non-empty `//` line is one message. Multi-line messages are
        // not supported in the comment-block shape — split them in source.
        foreach ($messageLines as $msg) {
            $result[$rector][] = $msg;
        }
    }

    return $result;
}
