<?php

$a = REQUIREMENT_INFO;
$b = REQUIREMENT_OK;
$c = REQUIREMENT_WARNING;
$d = REQUIREMENT_ERROR;
$other = OTHER_CONSTANT;

?>
-----
<?php

$a = \Drupal\Core\Extension\Requirement\RequirementSeverity::Info;
$b = \Drupal\Core\Extension\Requirement\RequirementSeverity::OK;
$c = \Drupal\Core\Extension\Requirement\RequirementSeverity::Warning;
$d = \Drupal\Core\Extension\Requirement\RequirementSeverity::Error;
$other = OTHER_CONSTANT;

?>
