<?php

declare(strict_types=1);

/**
 * Auto-generated by scripts/generate-coverage-registry.php.
 *
 * Do not edit by hand. Source of truth:
 *   - public const PHPSTAN_MESSAGES on each rector class
 *   - // PHPSTAN_MESSAGES: comment blocks above config-only registrations
 *
 * Messages are stored AFTER applying the three normalization transforms
 * upgrade_status's DeprecationAnalyzer::categorizeMessage() applies before
 * isRectorCovered(): whitespace collapse, ":\s+(in|as of)" → ". Deprecated
 * \1", and "Use \Drupal" → "Use Drupal".
 *
 * Consumers can require this file and either iterate by rector class, or
 * flatten with array_merge(...array_values($registry)) to get a flat list
 * of all covered deprecation strings.
 */

return array (
  'GetDrupalRootToRootPropertyRector' => 
  array (
    0 => 'Call to deprecated method getDrupalRoot() of class Drupal\\KernelTests\\KernelTestBase. Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Access $this->root directly.',
    1 => 'Call to deprecated method getDrupalRoot() of class Drupal\\Tests\\BrowserTestBase. Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Access $this->root directly.',
    2 => 'Call to deprecated method getDrupalRoot() of class Drupal\\Tests\\UnitTestCase. Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Access $this->root directly.',
  ),
  'RemoveAliasManagerCacheMethodCallsRector' => 
  array (
    0 => 'Call to deprecated method setCacheKey() of class Drupal\\path_alias\\AliasManager. Deprecated in drupal:11.3.0 and is removed from drupal:13.0.0. There is no replacement.',
    1 => 'Call to deprecated method writeCache() of class Drupal\\path_alias\\AliasManager. Deprecated in drupal:11.3.0 and is removed from drupal:13.0.0. There is no replacement.',
  ),
  'RemoveDrupalToStringTraitRector' => 
  array (
    0 => 'Usage of deprecated trait Drupal\\Component\\Utility\\ToStringTrait. Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Implement the __toString() method directly, exception handling is no longer required.',
  ),
  'RemoveRendererAddCacheableDependencyNonObjectRector' => 
  array (
    0 => 'Calling Drupal\\Core\\Render\\Renderer::addCacheableDependency() with an object that doesn\'t implement Drupal\\Core\\Cache\\CacheableDependencyInterface is deprecated in drupal:11.3.0 and will throw an error in drupal:13.0.0. See https://www.drupal.org/node/3525389',
  ),
  'ReplaceExpectDeprecationRector' => 
  array (
    0 => 'Call to deprecated method expectDeprecation() of class Drupal\\KernelTests\\KernelTestBase. Deprecated in drupal:11.4.0 and is removed from drupal:12.0.0. Use $this->expectUserDeprecationMessage() or $this->expectUserDeprecationMessageMatches() instead.',
  ),
  'ReplaceNodeViewControllerRector' => 
  array (
    0 => 'Instantiation of deprecated class Drupal\\node\\Controller\\NodeViewController. Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Use Drupal\\Core\\Entity\\Controller\\EntityViewController instead.',
  ),
  'UserLoadByNameAndMailRector' => 
  array (
    0 => 'Call to deprecated function user_load_by_mail(). Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Use Drupal::entityTypeManager()->getStorage(\'user\')->loadByProperties() instead.',
    1 => 'Call to deprecated function user_load_by_name(). Deprecated in drupal:11.4.0 and is removed from drupal:13.0.0. Use Drupal::entityTypeManager()->getStorage(\'user\')->loadByProperties() instead.',
  ),
);
