<?php

use Drupal\datetime_range\DateTimeRangeConstantsInterface;

$a = DateTimeRangeConstantsInterface::BOTH;
$b = DateTimeRangeConstantsInterface::START_DATE;
$c = DateTimeRangeConstantsInterface::END_DATE;
datetime_type_field_views_data_helper($field_storage, $data, 'value');

?>
-----
<?php

use Drupal\datetime_range\DateTimeRangeConstantsInterface;

$a = DateTimeRangeConstantsInterface::BOTH;
$b = DateTimeRangeConstantsInterface::START_DATE;
$c = DateTimeRangeConstantsInterface::END_DATE;
datetime_type_field_views_data_helper($field_storage, $data, 'value');

?>
